const MINUTS_IN_HOUR = 60;
const HOURS_IN_DAY = 24;

const DATE_FORMAT = 'MMM D';
const DATE_TIME_FORMAT = 'DD/MM/YY HH:mm';
const TIME_FORMAT = 'HH:mm';

export { MINUTS_IN_HOUR, HOURS_IN_DAY,DATE_FORMAT, DATE_TIME_FORMAT, TIME_FORMAT };
